name: Rollback Release

on:
  workflow_dispatch:

jobs:
  rollback: 
    runs-on: ubuntu-latest
    env:
      RELEASES_PATH: /var/www/livewire-wireui.com/releases
      CURRENT_RELEASE_PATH: /var/www/livewire-wireui.com/releases/current
 
    steps:
      - name: Rollback Release
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd ${{ env.RELEASES_PATH }}
            
            if [ $(ls -1q | wc -l) -ge 3 ] && [ -e ${{ env.CURRENT_RELEASE_PATH }} ]; then
              ln -nfs $(ls -r | grep '^[0-9]' | head -2 | tail -1) ${{ env.CURRENT_RELEASE_PATH }}
              rm -rf $(ls -r | grep '^[0-9]' | head -1)
            else
              echo "You don't have any release to rollback"
            fi
